language: scala
sudo: false
scala:
- 2.11.8
- 2.12.4
jdk:
- oraclejdk8
script: "./travis.sh"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt"
before_install:
- openssl aes-256-cbc -K $encrypted_f670d60e31ff_key -iv $encrypted_f670d60e31ff_iv
  -in .credentials.enc -out .credentials -d
env:
  global:
  - secure: AWYOpiKyTO2791MUSgjTktFZY3H/dT6IWQ8RcEKNkMmm9xCNDVC8o8qQNomHQ46lbagSFE4PtHnrQH+XmUclss/vlGc670s77G4I8u/+wqLBJzTuQwSEmh8lEdVPcwNCWWnl9+QNyeMNk3mRDVHwQwHFPa2NNN9eYrb9Jv+VM8L5Btrh6TH4HOlByBqAIrNhM4lWuP7GmNglTcJed4VDZoRp4NgRjy+5JxRAW+EMfRgWQjJN99e/dC+JQ8yytbA/7IjLO/EtUSN+Da2eOuX236qmMTc8lwn8NYyAS3zGpvvbFlNx2QScI/LgzDHla9b2ZfF0Af8LsyXvgBWxz95pUjEJL0Pcw8MNYuTT+dekiWjXf4ExqQGvQWudLlbr+UGVNzqQIyM/ntZTcYgYa30vXM84vgtm0HZaz+tvJXOLFXLl+WmR4lHGqAZr41CVwJ/PDYc8w4a5mvMSP1dSI9rCNKT6pwbqZsD9X+3Iscg5BGNn8P5745pEHxuvRX7+thotF5dlo4XITBZZDCE7TPvASy6s+guZ1yevIS9Hnq+sO4U4dhZTMCbs5w/ClBHSqVK04DyNm7rKEJrnZtlLrNOQjQhDBFTfpacLXPGG8p6CeaGmlRWsRiX0TavRLduad9dxB0cLsDGaVJXa9N43j0MhFsGlOxoZGq45qhw9KJPohrw=
  - secure: Hr2/AzBvQ2hccXQUE69eOeK2vk+hXd+HDcwC1L4we/I+f5HqLa/KXbN4ELHJUnxx/OALMxEga86aqayzcHLQ7ZLwWWzUkHJwCvmJP78K7e83tpEWAFqTXTHNrZNBZ/mpl0eGi77FHl2VaGQ05ar2AcuYrWEckNAXThCAL3K5/P0miaSPsrIOSwsm53HCpqCLWvfWBA5a4KgXM0AD1x/PXp9CKnhsM/dC4g8+iZEpVi1ClAf+SGsw8e8MgpNJqd0dJcptYEBEWVJa4DBo+U7C3+bR4KbbmAEW+3bDhw+T9BZa5AApu/4AzoUEwLHjnBMSJ7+SEFdHJohHRajNgBMS9yv3OT0DPoCERyVQNyTn1Lr3+bOx2/+Gneq1fm1AjxQkVoczAONrJNorCsglVfwDzqZCCZJ4zq6s8cGGtYM30pb2SslLSrowFBQAXQzL6Jk4xSsdIHc7ZjvtvQo/eVow8OjY9PXYhl0avl6QpVHkIeshFw1WwFn4BVszVFIon94LXYj+o3QF5JfDz+bKmIsAx2ZhRk0o4qayTijDYAOOIvfgSZpW1LsHhXihR0H+2pmcns7fJyFqHC4wsi8fMhBnGME2h2PAyYeRQxq33Tzm72UPiDe6+ltmcIvOZzOsmXkL7iVI204+AwHjrf87afyWVOhibaOTjDNeeI12cGEmvMA=
