language: scala
sudo: false
scala:
- 2.11.8
- 2.12.4
jdk:
- oraclejdk8
script: "./travis.sh"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt"
env:
  global:
  - secure: bltuNZAMq44jNOSxa28gstg2/GrDO+wAdZ6uPQiW5CoCLw1GHPuz54z89t8HznfPQMVaBCbUqFGMoTUQa4re8YgbcA8GHtP83R+gdGZX95MiaLjqTSD7Pzru9QTJEqIoIRMN+Mk6oAbQ/TW2ltc0qGYwv356Hsj7UNsQ/uD4Ps95L6AMW35l6EXHXXJhyBF/qajfOe+el2y83TsOo21uqc+gIRa3BnlGN9H2bP2rcA2zjGPaRUMhc8HHPYKyvfgSNsRtiF0R1Gp7oSPP4aR5ZkZXqdTHBuMixErUFfEqo1FmjgHiItvGpYMNNpwRVZ+e15jgU2xwrGMkY7UTbyOdQzK7ziu82r3dXZirqhWUzEEys+AWzmh+GYQ1ABcSH5gLGqivRSDaF6OIWKxSTQy0ubXj/0qltwiqkCZ68wbsmVxEuFv01MRCO+swnVf+iaZfUZg4D3hLAhf80JxUhGP2APi7ytprjOnhHp/iLR6QPEeCwpnq2PqKEZ+nO67rWH2Y4kHLSVu4Y92yN9hyrW2ofFeSPsOzDMrVrPWbriapp8guJn/NGfOvDeQf1jFqZmqrihoPEI7tRuFobT+OM0flcBbNLedBaReG1JMkRl4UWTEvND20kbEu/qyKX+jtcj4QmU8WAZufCHomJh5YmUOw6mOTRKXL5G0vxlDDS8TfhtY=
  - secure: ZZb44YwbVApnRMoy1vXVawsAmyhJMadWZyf54oK/mFDaDLNQTzU/Fzad+/fR3bF0yWoBBWsgrSn2CAN038wB0WD+RQnSUA6oRGiXXPpNQ5bhGkg55ljQ4mZSc3iYTgxwh+enbTh28S+OtwiF2oxGzovUZmfHOlB3nKoNtpPqvy4EJaFLhjktVz6D8DHOygzO6oZBkn4bqRjyc3HdFpDOotNeFy95vBrC8B8T7q02454OkuXFndZ3fJLufNGjzzNR548GnI345k44iuxmNcJKty3dz7OzUXfMOgB8C/7WkSS3k9HCSTUH/JndwMQtDARsjlD14GL52JI16ZWmN9GICPgAbF28zmZppoNGh1D2EK+jrHeutV3uKQH6HxRHAd3ZvMW89QyiUnTc4JbA7VdaknfPVts8gIgaKkXSR4lPqEtdjX6PYkU3bkAwUWRnNWmceOsiKs+kH4X6GAYP13m6VjeZgpQ+/9t0uagdjaX3iIuzePIECGO0/7Gby5lYHAZugzJg2y2Ws2FPouHddyP+cZ3LQF5EUNUpUQ+CqxhmN0xxFRDYOA+EsDWyIGo5+EjaoqjZpX4wiP0uyRSYo52VF4bifTJ9Pbbq5cHRBGG5mYZnm12kkif3RujGb672UipKZF1dVinFjEwaN6ZstniLG0fL3it5/IncCYmrvp5JRNk=
before_install:
- openssl aes-256-cbc -K $encrypted_e4c36b6f653a_key -iv $encrypted_e4c36b6f653a_iv
  -in .credentials.enc -out .credentials -d
