version: '3'
services:
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    ports:
      - 9201:9200
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9202:9200
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"